function phcholnp(varargin);
% phcholnp( [...] );
% Laser N Pts
h = timeplot({'NPts_Online','NPts_Offline'}, ...
      'Laser N Pts', ...
      'N Pts', ...
      {'NPts\_Online','NPts\_Offline'}, ...
      varargin{:} );
