function phchohcv(varargin);
% phchohcv( [...] );
% Htr Ctrl V
h = timeplot({'HtrDAC1_SP','HtrDAC1_RB','HtrDAC2_SP','HtrDAC2_RB','HtrADC1','HtrADC2'}, ...
      'Htr Ctrl V', ...
      'V', ...
      {'HtrDAC1\_SP','HtrDAC1\_RB','HtrDAC2\_SP','HtrDAC2\_RB','HtrADC1','HtrADC2'}, ...
      varargin{:} );
