function phchohgeshge(varargin);
% phchohgeshge( [...] );
% HG Errors SHG Errors
h = timeplot({'SHG_ErrorNumber','SHG_ErrorInstance','SHG_ErrorParameter'}, ...
      'HG Errors SHG Errors', ...
      'SHG Errors', ...
      {'SHG\_ErrorNumber','SHG\_ErrorInstance','SHG\_ErrorParameter'}, ...
      varargin{:} );
