function phchotflp(varargin);
% phchotflp( [...] );
% TFL Power
h = timeplot({'TFL_SDM_P','TFL_P2DMin_P','TFL_P2DMout_P'}, ...
      'TFL Power', ...
      'Power', ...
      {'TFL\_SDM\_P','TFL\_P2DMin\_P','TFL\_P2DMout\_P'}, ...
      varargin{:} );
