function phchoppsd(varargin);
% phchoppsd( [...] );
% PPS Drift
h = timeplot({'PPS_drift','PPS_min_drift'}, ...
      'PPS Drift', ...
      'Drift', ...
      {'PPS\_drift','PPS\_min\_drift'}, ...
      varargin{:} );
