function phchohgshgv(varargin);
% phchohgshgv( [...] );
% HG SHG Voltage
h = timeplot({'SHG_OutputVoltage'}, ...
      'HG SHG Voltage', ...
      'Voltage', ...
      {'SHG\_OutputVoltage'}, ...
      varargin{:} );
