function phchohgthgs(varargin);
% phchohgthgs( [...] );
% HG THG Status
h = timeplot({'THG_DevStatus'}, ...
      'HG THG Status', ...
      'Status', ...
      {'THG\_DevStatus'}, ...
      varargin{:} );
