function phchotflhgt(varargin);
% phchotflhgt( [...] );
% TFL HGT
h = timeplot({'TFL_SHG','TFL_SHG_SP','TFL_THG','TFL_THG_SP'}, ...
      'TFL HGT', ...
      'HGT', ...
      {'TFL\_SHG','TFL\_SHG\_SP','TFL\_THG','TFL\_THG\_SP'}, ...
      varargin{:} );
