function phchohgthgc(varargin);
% phchohgthgc( [...] );
% HG THG Current
h = timeplot({'THG_OutputCurrent'}, ...
      'HG THG Current', ...
      'Current', ...
      {'THG\_OutputCurrent'}, ...
      varargin{:} );
