function phchotfla(varargin);
% phchotfla( [...] );
% TFL mA
h = timeplot({'TFL_SD_I','TFL_P2D_I'}, ...
      'TFL mA', ...
      'mA', ...
      {'TFL\_SD\_I','TFL\_P2D\_I'}, ...
      varargin{:} );
