function phchohgsmes(varargin);
% phchohgsmes( [...] );
% HG Stale ME Stale
h = timeplot({'HG_Stale'}, ...
      'HG Stale ME Stale', ...
      'ME Stale', ...
      {'HG\_Stale'}, ...
      varargin{:} );
