function phchomlp(varargin);
% phchomlp( [...] );
% Monitor Laser P
h = timeplot({'BCtr_LasIn_mW','LasOut_mW'}, ...
      'Monitor Laser P', ...
      'Laser P', ...
      {'BCtr\_LasIn\_mW','LasOut\_mW'}, ...
      varargin{:} );
