function phchobcc(varargin);
% phchobcc( [...] );
% B Ctr Cts
h = timeplot({'BCtr_0_a','BCtr_1_a'}, ...
      'B Ctr Cts', ...
      'Cts', ...
      {'BCtr\_0\_a','BCtr\_1\_a'}, ...
      varargin{:} );
