function phchohgshgc(varargin);
% phchohgshgc( [...] );
% HG SHG Current
h = timeplot({'SHG_OutputCurrent'}, ...
      'HG SHG Current', ...
      'Current', ...
      {'SHG\_OutputCurrent'}, ...
      varargin{:} );
