function phchohgsshgs(varargin);
% phchohgsshgs( [...] );
% HG Stale SHG Stale
h = timeplot({'SHG_Stale'}, ...
      'HG Stale SHG Stale', ...
      'SHG Stale', ...
      {'SHG\_Stale'}, ...
      varargin{:} );
