function phchotflhgt(varargin);
% phchotflhgt( [...] );
% TFL HGT
h = timeplot({'TFL_SHG','TFL_THG'}, ...
      'TFL HGT', ...
      'HGT', ...
      {'TFL\_SHG','TFL\_THG'}, ...
      varargin{:} );
