function phchotsv(varargin);
% phchotsv( [...] );
% Temp Sensors Volts
h = timeplot({'TS1_T','TS3_T','TS5_T'}, ...
      'Temp Sensors Volts', ...
      'Volts', ...
      {'TS1\_T','TS3\_T','TS5\_T'}, ...
      varargin{:} );
