function phchoswsd(varargin);
% phchoswsd( [...] );
% SW Status Delta
h = timeplot({'Offline_Delta'}, ...
      'SW Status Delta', ...
      'Delta', ...
      {'Offline\_Delta'}, ...
      varargin{:} );
