function phchofccflow1(varargin);
% phchofccflow1( [...] );
% FCC Flow 1
h = timeplot({'FC1_Flow','FC1_Set'}, ...
      'FCC Flow 1', ...
      'Flow 1', ...
      {'FC1\_Flow','FC1\_Set'}, ...
      varargin{:} );
