function phchohcv(varargin);
% phchohcv( [...] );
% Htr Ctrl V
h = timeplot({'HtrDAC1_SP','HtrDAC1_RB','HtrADC1'}, ...
      'Htr Ctrl V', ...
      'V', ...
      {'HtrDAC1\_SP','HtrDAC1\_RB','HtrADC1'}, ...
      varargin{:} );
