function phchohgthgt(varargin);
% phchohgthgt( [...] );
% HG THG Temp
h = timeplot({'THG_T','THG_Set_T'}, ...
      'HG THG Temp', ...
      'Temp', ...
      {'THG\_T','THG\_Set\_T'}, ...
      varargin{:} );
