function phchobclp(varargin);
% phchobclp( [...] );
% B Ctr Laser P
h = timeplot({'BCtr_LasIn_mW'}, ...
      'B Ctr Laser P', ...
      'Laser P', ...
      {'BCtr\_LasIn\_mW'}, ...
      varargin{:} );
