function phchotsc(varargin);
% phchotsc( [...] );
% Temp Sensors Count
h = timeplot({'TS1_cnt','TS3_cnt','TS5_cnt'}, ...
      'Temp Sensors Count', ...
      'Count', ...
      {'TS1\_cnt','TS3\_cnt','TS5\_cnt'}, ...
      varargin{:} );
