function phchohgthgv(varargin);
% phchohgthgv( [...] );
% HG THG Voltage
h = timeplot({'THG_OutputVoltage'}, ...
      'HG THG Voltage', ...
      'Voltage', ...
      {'THG\_OutputVoltage'}, ...
      varargin{:} );
