function phchohgsthgs(varargin);
% phchohgsthgs( [...] );
% HG Stale THG Stale
h = timeplot({'THG_Stale'}, ...
      'HG Stale THG Stale', ...
      'THG Stale', ...
      {'THG\_Stale'}, ...
      varargin{:} );
