function phchohgshgt(varargin);
% phchohgshgt( [...] );
% HG SHG Temp
h = timeplot({'SHG_T','SHG_Set_T'}, ...
      'HG SHG Temp', ...
      'Temp', ...
      {'SHG\_T','SHG\_Set\_T'}, ...
      varargin{:} );
