function phchofcct(varargin);
% phchofcct( [...] );
% FCC Temps
h = timeplot({'FCC_U2_T','FCC_U3_T'}, ...
      'FCC Temps', ...
      'Temps', ...
      {'FCC\_U2\_T','FCC\_U3\_T'}, ...
      varargin{:} );
