function phchoswssws(varargin);
% phchoswssws( [...] );
% SW Status SW Stat
h = timeplot({'SWStat'}, ...
      'SW Status SW Stat', ...
      'SW Stat', ...
      {'SWStat'}, ...
      varargin{:} );
