function phcholv(varargin);
% phcholv( [...] );
% Laser Volts
h = timeplot({'LaserV','LV_start','LV_stop','LV_online','LV_offline'}, ...
      'Laser Volts', ...
      'Volts', ...
      {'LaserV','LV\_start','LV\_stop','LV\_online','LV\_offline'}, ...
      varargin{:} );
