function phchohgethge(varargin);
% phchohgethge( [...] );
% HG Errors THG Errors
h = timeplot({'THG_ErrorNumber','THG_ErrorInstance','THG_ErrorParameter'}, ...
      'HG Errors THG Errors', ...
      'THG Errors', ...
      {'THG\_ErrorNumber','THG\_ErrorInstance','THG\_ErrorParameter'}, ...
      varargin{:} );
