function phchols(varargin);
% phchols( [...] );
% Laser Step
h = timeplot({'LV_step','LV_dither'}, ...
      'Laser Step', ...
      'Step', ...
      {'LV\_step','LV\_dither'}, ...
      varargin{:} );
