function phchohgshgt(varargin);
% phchohgshgt( [...] );
% HG SHG Temp
h = timeplot({'SHG_T','SHG_Set_T','SHG_Sink_T'}, ...
      'HG SHG Temp', ...
      'Temp', ...
      {'SHG\_T','SHG\_Set\_T','SHG\_Sink\_T'}, ...
      varargin{:} );
