function phcholhks(varargin);
% phcholhks( [...] );
% Laser HK Step
h = timeplot({'LV_step','LV_offdelta','LV_dither'}, ...
      'Laser HK Step', ...
      'Step', ...
      {'LV\_step','LV\_offdelta','LV\_dither'}, ...
      varargin{:} );
