function phcholhknp(varargin);
% phcholhknp( [...] );
% Laser HK N Pts
h = timeplot({'NPts_Online','NPts_Offline'}, ...
      'Laser HK N Pts', ...
      'N Pts', ...
      {'NPts\_Online','NPts\_Offline'}, ...
      varargin{:} );
