function phchofccf(varargin);
% phchofccf( [...] );
% FCC Flow 0
h = timeplot({'FC0_Flow','FC0_Set'}, ...
      'FCC Flow 0', ...
      'Flow 0', ...
      {'FC0\_Flow','FC0\_Set'}, ...
      varargin{:} );
