function phchofccflow2(varargin);
% phchofccflow2( [...] );
% FCC Flow 2
h = timeplot({'FC2_Flow','FC2_Set'}, ...
      'FCC Flow 2', ...
      'Flow 2', ...
      {'FC2\_Flow','FC2\_Set'}, ...
      varargin{:} );
