function phchotst(varargin);
% phchotst( [...] );
% Temp Sensors Temp
h = timeplot({'TS0_T','TS1_T','TS2_T','TS3_T','TS4_T','TS5_T'}, ...
      'Temp Sensors Temp', ...
      'Temp', ...
      {'TS0\_T','TS1\_T','TS2\_T','TS3\_T','TS4\_T','TS5\_T'}, ...
      varargin{:} );
