function phchohgshgs(varargin);
% phchohgshgs( [...] );
% HG SHG Status
h = timeplot({'SHG_DevStatus'}, ...
      'HG SHG Status', ...
      'Status', ...
      {'SHG\_DevStatus'}, ...
      varargin{:} );
