function phchotflamps(varargin);
% phchotflamps( [...] );
% TFL Amps
h = timeplot({'TFL_P1D_I','TFL_P1D_I_SP'}, ...
      'TFL Amps', ...
      'Amps', ...
      {'TFL\_P1D\_I','TFL\_P1D\_I\_SP'}, ...
      varargin{:} );
