function phchoswsnp(varargin);
% phchoswsnp( [...] );
% SW Status N Pts
h = timeplot({'NPts_Online','NPts_Offline'}, ...
      'SW Status N Pts', ...
      'N Pts', ...
      {'NPts\_Online','NPts\_Offline'}, ...
      varargin{:} );
