function phchohcs(varargin);
% phchohcs( [...] );
% Htr Ctrl Status
h = ne_dstat({
  'HtrDAC1_Fresh', 'Htr_Status', 7; ...
	'HtrDAC2_Fresh', 'Htr_Status', 11; ...
	'HtrADC1_Fresh', 'Htr_Status', 2; ...
	'HtrADC2_Fresh', 'Htr_Status', 3 }, 'Status', varargin{:} );
